export enum ThemeAspects {
  PAGE_TOOLBAR = 'layout-toolbar',
  PAGE_BACKGROUND = 'layout-background',
  PAGE_FOOTER = 'layout-footer',
  PAGE_NAVPANEL = 'layout-navpanel',
  PAGE_CONTENT = 'layout-content',
  PAGE_CONTAINER = 'layout-container',
  COLOR_PRIMARY = 'color-primary',
  COLOR_ACCENT = 'color-secondary',
  COLOR_ERROR = 'color-error',
  COLOR_WARN = 'color-warn',
  TEXT_TITLE = 'text-title',
  TEXT_SUBTITLE = 'text-subtitle',
  TEXT_HEADER = 'text-header',
  TEXT_PARRAGRAPH = 'text-parragraph',
  BUTTON_PRIMARY = 'button-primary',
  BUTTON_ACCENT = 'button-secondary',
  USER_AVATAR = 'user-avatar',
  USER_BACKGROUND = 'user-background',
  USER_NAMEDISPLAY = 'user-namedisplay',
}
